### ISSUE TITLE
Error after some time

### ISSUE THREAD

**Issue by Isitsmd** [ashrafdx1/eth200swinger#1]
Traceback (most recent call last):
  File "C:\Users\MD\Downloads\Imp\swig\swig.py", line 470, in <module>
    main()
  File "C:\Users\MD\Downloads\Imp\swig\swig.py", line 196, in main
    privatekeyStart = int(skipdups(prefixes),16)
  File "C:\Users\MD\Downloads\Imp\swig\swig.py", line 171, in skipdups
    nodups =nodups + prefixes[counter][2]
IndexError: string index out of range

**Comment by ashrafdx1** [comment]
alright.. just a sec to fix it..
